### ISSUE TITLE
Resource Browser not available for all directories

### ISSUE THREAD

**Issue by dawgermany** [opengisch/qgis-conda-builder#4]
<img width="912" alt="Bildschirmfoto 2023-10-23 um 12 14 51" src="https://github.com/opengisch/qgis-conda-builder/assets/15872836/c77cfc29-6c7c-4723-b8b7-9a178ac906f9">
Hey, first of all thanks for the updated Mac Packages; really aprecciate it 💯.
I have an issue in which i open a project inside a folder on the desktop and all the files were unlinked.Auto-search did not work even after manually relinking a single file. then i tried using the data source manager and it did not show contents of for example the folder Desktop and Documents. relinking a single file works and the contents are shown on the map. Usually mac applications try to ask for permission accessing these Folders, which did not happen. In combination with this error message i suspect some form of permissions not being consistently correct.

**Comment by joaoponceleao** [comment]
Can confirm issue on my system. Adding Qgis.app (or qgis bin inside the .app) to MacOS full disk permissions does not solve the issue.

**Comment by m-kuhn** [comment]
There will be an updated release available in 30 minutes, which includes https://github.com/opengisch/constructor/commit/5dd7ddaddc88bfd21e2431bda13d873aff67a1d1 . The error from the screenshot should be gone and it's possible that (at least some of) the problems are linked to missing providers, which should be fixed now. If there is still something regarding permissions that will need to be investigated separately.

**Comment by joaoponceleao** [comment]
Think we can close this following the latest fix.

**Comment by m-kuhn** [comment]
Great new.
Thank you for testing.
