### ISSUE TITLE
Wrong plugins path

### ISSUE THREAD

**Issue by joaoponceleao** [opengisch/qgis-conda-builder#5]
Upon starting QGIS, processing is not available (among other issues). Starting plugin manager gives the following error:
`No QGIS plugins found in /Users/joao/Applications/QGIS-3.32.app/Contents/QGIS.app/Contents/MacOS/lib/qgis/plugins`

The path should probably be $HOME/Applications/QGIS-3.32.app/Contents/plugins ?

**Comment by dawgermany** [comment]
Plugin manager also does not load the plugin store (the list of plugins available for download)
The settings panel in the plugin manager looks like this
<img width="899" alt="Bildschirmfoto 2023-10-23 um 13 02 47" src="https://github.com/opengisch/qgis-conda-builder/assets/15872836/709e83a6-3274-4765-ba75-0ef1439a9506">

**Comment by m-kuhn** [comment]
https://github.com/opengisch/constructor/commit/5dd7ddaddc88bfd21e2431bda13d873aff67a1d1 should be a bandaid for this

**Comment by joaoponceleao** [comment]
Thanks for the fix! Everything seems good.

**Comment by dawgermany** [comment]
> Thanks for the fix! Everything seems good.

how did you test this? i cannot see a new build in the release list... 🙃

**Comment by joaoponceleao** [comment]
It's there. It's not marked as a new release (since it isn't), but the package is updated
