### ISSUE TITLE
Processing not available; Algorithms and tools not available

### ISSUE THREAD

**Issue by dawgermany** [opengisch/qgis-conda-builder#8]
I cannot find anything related to processing; no python console, no processing toolbox -> no algorithms

**Comment by m-kuhn** [comment]
https://github.com/opengisch/constructor/commit/5dd7ddaddc88bfd21e2431bda13d873aff67a1d1 should be a bandaid for this

**Comment by joaoponceleao** [comment]
Think this can be closed as fixed now.
